### ISSUE TITLE
Error after running  `pip install -e . --upgrade`

### ISSUE THREAD

**Issue by JBrandh** [matthiaskoenig/sbmlsim#112]
Running ´pip install -e . --upgrade´ returns

ERROR: Cannot install libroadrunner==2.0.5, sbmlsim and sbmlsim==0.2.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    sbmlsim 0.2.0 depends on numpy>=1.21.0
    altair 4.1.0 depends on numpy
    biosimulators-utils 0.1.93 depends on numpy
    bottleneck 1.3.2 depends on numpy
    libroadrunner 2.0.5 depends on numpy==1.19.3

**Comment by matthiaskoenig** [comment]
This is already solved with some latest dependency updates. I will make a new release in the next few days.
