### ISSUE TITLE
Support python 3.9

### ISSUE THREAD

**Issue by matthiaskoenig** [matthiaskoenig/sbmlsim#75]
Currently no python 3.9 support by ray.
See https://github.com/ray-project/ray/issues/11287
```
ERROR: Could not find a version that satisfies the requirement ray (from versions: none)
ERROR: No matching distribution found for ray
```

**Comment by daniel347x** [comment]
Please forgive me if this is inappropriate to ask, as I am grateful for the effort folks have put into the Ray library, but is there a timeline for this? The lack of support of Ray for Python 3.9 is the only thing holding me back from upgrading to Python 3.9 at this point, and there is no good substitute for Ray as an improvement upon Python.Multiprocessing.

**Comment by matthiaskoenig** [comment]
@daniel347x You posted on the wrong issue. I just linked the ray issue because I am in the same position as you (just waiting for ray to finally have py3.9 support. Please post your comment on
See ray-project/ray#11287
and delete it here.

Best Matthias
